-- Create Contacts Table
CREATE TABLE Contacts (
    contact_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    f_name VARCHAR2(50) NOT NULL,
    l_name VARCHAR2(50) NOT NULL,
    organization VARCHAR2(100),
    title VARCHAR2(50),
    email VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20)
);

-- Invitations Table
CREATE TABLE Invitations (
    invitation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id NUMBER,
    date_sent DATE NOT NULL,
    response VARCHAR2(20),
    FOREIGN KEY (contact_id) REFERENCES Contacts(contact_id)
);


-- Create Registration Table
CREATE TABLE Registration (
    registration_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id INT,
    date_link_sent DATE NOT NULL,
    form_completed NUMBER(1) DEFAULT 0,
    FOREIGN KEY (contact_id) REFERENCES Contacts(contact_id)
);

-- Create Hotel_Bookings Table
CREATE TABLE Hotel_Bookings (
    hotel_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id INT,
    date_link_sent DATE NOT NULL,
    form_completed NUMBER(1) DEFAULT 0,
    hotel_name VARCHAR2(100),
    check_in DATE,
    check_out DATE,
    cost DECIMAL(10, 2),
    charges DECIMAL(10, 2),
    FOREIGN KEY (contact_id) REFERENCES Contacts(contact_id)
);

-- Create Flights Table
CREATE TABLE Flights (
    flightID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id INT,
    date_link_sent DATE NOT NULL,
    form_completed NUMBER(1) DEFAULT 0,
    flight_num VARCHAR2(10),
    arrival_date DATE,
    departure_date DATE,
    cost DECIMAL(10, 2),
    FOREIGN KEY (contact_id) REFERENCES Contacts(contact_id)
);

-- Create Session_Attendance Table
CREATE TABLE Session_Attendance (
    session_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id INT,
    attended_status VARCHAR2(15),
    FOREIGN KEY (contact_id) REFERENCES Contacts(contact_id)
);
